---
apiVersion: v1
kind: Pod
metadata:
 name: postgres-pod
 labels:
  type: db
  author: krishna
spec:
 containers:
  - name: mydb
    image: postgres
    env:
     - name: POSTGRES_PASSWORD
       value: krishna
     - name: POSTGRES_USER
       value: myuser
     - name: POSTGRES_DB
       value: hbc_db

