---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    type: db
spec:
  containers:
    - name: mydb
      image: mysql:5
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: krishna
  tolerations:
    - key: slave2
      value: node2
      effect: NoSchedule
      operator: Equal
      
...
